'use strict';

var EnumServiceState = {
	CREATED: 				'CREATED',
	ASSIGNED: 				'ASSIGNED',
	COMPLETED: 				'COMPLETED',
	DESISTED: 				'DESISTED',
	ABANDONED_BY_GAMBLER: 	'ABANDONED_BY_GAMBLER',
	ABANDONED_BY_TRADER: 	'ABANDONED_BY_TRADER',
	CANCELED: 				'CANCELED'
};

module.exports = EnumServiceState;