'use strict';

var EnumServiceState = {
	CREATED: 				'CREATED',
	PROCESSING:				'PROCESSING',
	COMPLETED: 				'COMPLETED',
	DESISTED: 				'DESISTED',
	ERROR: 					'ERROR',
	ABANDONED_BY_BANK: 		'ABANDONED_BY_BANK',
	ABANDONED_BY_GAMBLER: 	'ABANDONED_BY_GAMBLER',
	ABANDONED_BY_TRADER: 	'ABANDONED_BY_TRADER'
};

module.exports = EnumServiceState;