'use strict';

var EnumServicesSocketEvent = {
	// Native events
	natives: {
		CONNECTION: 	'connect',
		DISCONNECT:		'disconnect',	
	},
	// App events
	app: {
		ABANDONED_BY_GAMBLER: 	'ABANDONED_BY_GAMBLER',
		ABANDONED_BY_TRADER: 	'ABANDONED_BY_TRADER',
		CREATE_SERVICE: 		'CREATE_SERVICE',
		CONNECTED_USER: 		'CONNECTED_USER',
		ERROR: 					'ERROR',
		NEW_MESSAGE_SERVICE:	'NEW_MESSAGE_SERVICE',
		NEW_SERVICE: 			'NEW_SERVICE',
		SHIFT_QUEUE: 			'SHIFT_QUEUE',
		START_WORK: 			'START_WORK',
		STOP_WORKING: 			'STOP_WORKING',
		SERVICE_CANCELED: 		'SERVICE_CANCELED',
		SERVICE_FINISHED: 		'SERVICE_FINISHED',
		TRADER_ASSIGNED: 		'TRADER_ASSIGNED ',
		TRADERS_AVAILABLE: 		'TRADERS_AVAILABLE'
	}
};

module.exports = EnumServicesSocketEvent;